
### Silhouette plot

<!-- Component created on {{ date }} -->

```{r, eval=!is_shiny}
sil_plot <- plotly::plot_ly(sd_{{ env_id }}, colors = "Set1") %>%
  plotly::add_bars(color = df_{{ env_id }}[[grouping]], name = df_{{ env_id }}[[grouping]], orientation = 'h', mode = "bar", y = ~cell, x = ~silhouette) %>%
  plotly::layout(yaxis = list(showticklabels = FALSE), showlegend = FALSE) %>%
  plotly::highlight(on = "plotly_selected", dynamic = F, selectize = F)
sil_plot
```

```{r, eval=is_shiny}
#
# Output
#
output$plot_sil_{{ env_id }} <- plotly::renderPlotly({
  sil_plot <- plotly::plot_ly(df_{{ env_id }}()$sd, colors = "Set1") %>%
  plotly::add_bars(color = df_{{ env_id }}()$df[[df_{{ env_id }}()$grouping]], name = df_{{ env_id }}()$df[[df_{{ env_id }}()$grouping]], orientation = 'h', mode = "bar", y = ~cell, x = ~silhouette) %>%
  plotly::layout(yaxis = list(showticklabels = FALSE), showlegend = FALSE) %>%
  plotly::highlight(on = "plotly_selected", dynamic = F, selectize = F)
  sil_plot
})

#
# Layout of component
#
plotly::plotlyOutput("plot_sil_{{ env_id }}", height = "100%")
```
