###

```{r, eval=!is_shiny}
DT::datatable(df_couns_stats_{{ env_id }}, filter = 'top', selection = list(mode = 'single', target = 'row'), 
              options = list(
    columnDefs = list(list(visible = FALSE, targets = c(1,2)))),
    callback=DT::JS("
  table.on('click.dt', 'tr', function() {
  var id = 'plot_{{ env_id }}';
  var data = table.row(this).data()[1];
  var featurename = table.row(this).data()[2];
  var gd = document.getElementById(id)
  var layout_update = {title: featurename};
  var expr = data.split(';').map(function(item){return parseFloat(item);});
  var min = Math.min(...expr);
  var max = Math.max(...expr);
  
  var data_update_0 = {
  'marker.color': [expr],
  'marker.cmax': max,
  'marker.cmin': min,
  'marker.line.cmin': min,
  'marker.line.cmax': max,
  'marker.line.color': [expr]};

  var data_update_1 = {
  'marker.color': [min, max],
  'marker.cmax': max,
  'marker.cmin': min};
  
  Plotly.restyle(id, data_update_0, [0]);
  Plotly.restyle(id, data_update_1, [1]);
  Plotly.relayout(id, layout_update);
  
  if ( $(this).hasClass('selected') ) {
      $(this).removeClass('selected');
  }
  else {
      table.$('tr.selected').removeClass('selected');
      $(this).addClass('selected');
  }
  
  /* console.log(featurename);
  console.log(expr);
  console.log(min);
  console.log(max);
  console.log(gd.data);
  console.log(gd.layout); */
});
")
)
```

```{r, eval=is_shiny}
output$tbl_{{ env_id }} <- DT::renderDataTable({
  options(DT.options = list(scrollY="400px",scrollX="300px", pageLength = 50, autoWidth = TRUE))
  DT::datatable(metadata_{{ env_id }}, filter = 'top', selection = list(mode = 'single', selected = 1, target = 'row'))
})

DT::dataTableOutput('tbl_{{ env_id }}')
```


