###

<!-- Component created on {{ date }} -->

```{r, eval=!is_shiny}
violins <- plotly::plot_ly(sd_{{ env_id }}, colors = "Set1", x = ~grouping, y = ~expression, color = ~grouping, type = "violin", box = list(visible = T), meanline = list(visible = T), points = "all", jitter = 0) %>%
    plotly::layout(
      xaxis = list(title = grouping),
      yaxis = list(title = "Expression per cluster"),
      showlegend = FALSE
    )
violins  %>% plotly::highlight(on = "plotly_selected", dynamic = F, selectize = F)
```

```{r, eval=is_shiny}
df2_{{ env_id }} <- shiny::reactive({
  keys <- plotly::event_data("plotly_selected", source = "scatter_{{ env_id }}")$key
  df <- df_{{ env_id }}()$df
  if(!is.null(keys)) df <- df[keys,]
  return(df)
})

output$plot_violin_{{ env_id }} <- plotly::renderPlotly({
  m <- df2_{{ env_id }}()[which.max(df2_{{ env_id }}()$expression),]
  a1 = list(x = ~unique(grouping), y = m$expression, text = ~filter_count, showarrow = F, yanchor = "bottom", yshift = 15)
  a2 = list(x = ~unique(grouping), y = m$expression, text = ~paste(rounded, "%"), showarrow = F, yanchor = "bottom")
  a1_desc = list(x = 0, y = m$expression, text = "<b>No. of pos. expression (>0):</b>", showarrow = F, xanchor = "left", yanchor = "bottom", yshift = 30, xshift = -30)

  violins <- plotly::plot_ly(df2_{{ env_id }}(), colors = "Set1", x = ~grouping, y = ~expression, color = ~grouping, type = "violin", box = list(visible = T), meanline = list(visible = T), points = "all", jitter = 0) %>%
    plotly::layout(
      xaxis = list(title = grouping),
      yaxis = list(title = "Expression per grouping"),
      showlegend = FALSE)

  df2_{{ env_id }}() %>%
    dplyr::group_by(grouping) %>%
    dplyr::summarise(total_count = n()) -> df1_summarized

  df2_{{ env_id }}() %>%
    dplyr::group_by(grouping) %>%
    dplyr::filter(expression > 0, .preserve = T) %>%
    dplyr::summarise(filter_count = n()) -> df2_summarized

  df1_summarized$filter_count <-  df2_summarized$filter_count
  df1_summarized %>%
    mutate(freq = filter_count * 100/ total_count) -> df_combined
  df_combined %<>%
    mutate(rounded = round(freq, 2))

  violins %<>% plotly::layout(data = df2_summarized, annotations = a1)
  violins %<>% plotly::layout(data = df_combined, annotations = a2)
  violins %<>% plotly::layout(annotations = a1_desc)
  violins
})
plotly::plotlyOutput("plot_violin_{{ env_id }}", height = "100%")
```



### No. of cells with positive expression (>0) {data-height=300}

```{r, eval=!is_shiny}
df1_summarized <- df_{{ env_id }} %>%
    dplyr::group_by(grouping, gene) %>%
    dplyr::summarise(total_count = n())

df2_summarized <- df_{{ env_id }} %>%
    dplyr::group_by(grouping, gene) %>%
    dplyr::filter(expression > 0, .preserve = T) %>%
    dplyr::summarise(no_pos_expr = n())

df1_summarized$no_pos_expr <- df2_summarized$no_pos_expr
df1_summarized %<>%
  mutate(freq = no_pos_expr * 100/ total_count)
df1_summarized %<>%
  mutate(rounded = round(freq, 2)) %>%
  mutate(final_str = paste0(no_pos_expr, " cells (", rounded, " %)")) %>%
  select(-c(total_count, no_pos_expr, freq, rounded)) %>%
  tidyr::spread(grouping, final_str)
DT::datatable(df1_summarized)
```

```{r, eval=is_shiny}
renderTable({
  df1_summarized <- df_{{ env_id }}()$table_df %>%
    dplyr::group_by(grouping, gene) %>%
    dplyr::summarise(total_count = n())
  
  df2_summarized <- df_{{ env_id }}()$table_df %>%
    dplyr::group_by(grouping, gene) %>%
    dplyr::filter(expression > 0, .preserve = T) %>%
    dplyr::summarise(no_pos_expr = n())

  df1_summarized$no_pos_expr <- df2_summarized$no_pos_expr
  df1_summarized %<>%
    mutate(freq = no_pos_expr * 100/ total_count)
  df1_summarized %<>%
    mutate(rounded = round(freq, 2)) %>%
    mutate(final_str = paste0(no_pos_expr, " cells (", rounded, " %)")) %>%
    select(-c(total_count, no_pos_expr, freq, rounded)) %>%
    tidyr::spread(grouping, final_str)
  df1_summarized 
})
```




