### {{ title }}

<!-- Component created on {{ date }} -->

```{r}
{{ env_id }} <- readRDS(file.path(datadir, "{{ env_id }}.rds"))
is_shiny <- identical(knitr::opts_knit$get("rmarkdown.runtime"), "shiny")
library(magrittr)
library(scater)
library(SummarizedExperiment)
```

```{r, eval=!is_shiny}
# create plot

params_{{ env_id }} <- list(
  object = {{ env_id }}$object,
  features = {{ env_id }}$features,
  x = {{ env_id }}$x,
  exprs_values = {{ env_id }}$exprs_values,
  ncol = {{ env_id }}$ncol,
  scales = {{ env_id }}$scales
)
params_{{ env_id }} <- append(params_{{ env_id }}, {{ env_id }}$params)

plot_{{ env_id }} <- do.call(scater::plotExpression, params_{{ env_id }})

# handle titles
if(!is.null({{ env_id }}$plot_title)) plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::ggtitle({{ env_id }}$plot_title)
if(!is.null({{ env_id }}$x_title)) plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::xlab({{ env_id }}$x_title)
if(!is.null({{ env_id }}$y_title)) plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::ylab({{ env_id }}$y_title)

# handle if as_plotly = TRUE
if({{ env_id }}$as_plotly){
  plot_{{ env_id }} <- plotly::ggplotly(plot_{{ env_id }})
}

# Provide data for download
download_{{ env_id }} <- data.frame(SummarizedExperiment::assay({{ env_id }}$object, {{ env_id }}$exprs_values)[{{ env_id }}$features,])
# todo: add metadata to the df


plot_{{ env_id }}

# to do: provide data for download, but the ggplot2 plot cannot be displayed in the div container
# Provide data for download
# if({{ env_id }}$from == "colData"){
#   download_{{ env_id }} <- data.frame(colData({{ env_id }}$object)[,c({{ env_id }}$y[1], {{ env_id }}$x[1], {{ env_id }}$metadata[1])])
# } else {
#   download_{{ env_id }} <- data.frame(rowData({{ env_id }}$object)[,c({{ env_id }}$y[1], {{ env_id }}$x[1], {{ env_id }}$metadata[1])])
# }

# generate component
# htmltools::div(style="display:block;float:left;width:100%;height:90%;",
#   htmltools::tags$button(i2dash::embed_var(download_{{ env_id }})), plot_{{ env_id }})
#htmltools::tags$button(i2dash::embed_var(download_{{ env_id }}))
```

```{r, eval=is_shiny}
selected_feat_{{ env_id }} <- NULL
selected_meta_{{ env_id }} <- NULL
if({{ env_id }}$x %in% {{ env_id }}$features) selected_feat_{{ env_id }} <- {{ env_id }}$x else selected_meta_{{ env_id }} <- {{ env_id }}$x 

# shiny input elements
ui_list <- list(
  # action button
  shiny::actionButton("generate_{{ env_id }}", label = "Generate plot"),
  # features
  shiny::selectInput("select_subset_{{ env_id }}", label = "Select features:", choices = {{ env_id }}$features, multiple = TRUE, selected = {{ env_id }}$features[1]),
  # group_by feature
  shiny::selectInput("select_group_feat_{{ env_id }}", label = "Group by feature:", choices = c("None", {{ env_id }}$features), selected = selected_feat_{{ env_id }}),
  # or group_by metadata
  shiny::selectInput("select_group_meta_{{ env_id }}", label = "Or group by metadata:", choices = c("None", {{ env_id }}$metadata), selected = selected_meta_{{ env_id }}),
  # colour_by feature
  shiny::selectInput("select_colour_feat_{{ env_id }}", label = "Colour by feature:", choices = c("None", {{ env_id }}$features)),
  # or colour_by metadata
  shiny::selectInput("select_colour_meta_{{ env_id }}", label = "Or colour by metadata:", choices = c("None", {{ env_id }}$metadata)),
  # shape_by feature
  shiny::selectInput("select_shape_feat_{{ env_id }}", label = "Shape by feature:", choices = c("None", {{ env_id }}$features)),
  # or shape_by metadata
  shiny::selectInput("select_shape_meta_{{ env_id }}", label = "Or shape by metadata:", choices = c("None", {{ env_id }}$metadata)),
  # size_by feature
  shiny::selectInput("select_size_feat_{{ env_id }}", label = "Size by feature:", choices = c("None", {{ env_id }}$features)),
  # or size_by metadata
  shiny::selectInput("select_size_meta_{{ env_id }}", label = "Or size by metadata:", choices = c("None", {{ env_id }}$metadata)),
  # ncols
  shiny::numericInput("select_ncol_{{ env_id }}", label = "Number of columns.", value = {{ env_id }}$ncol),
  # or size_by metadata
  shiny::selectInput("select_scales_{{ env_id }}", label = "Select multi-facet scales:", choices = c("fixed", "free", "free_x", "free_y"), selected = {{ env_id }}$scales),
  # download
  tags$div(tags$br(), downloadButton('downloadData_{{ env_id }}', 'Download data'))
)

# handle arguments
reactive_{{ env_id }} <- shiny::reactive({
  # set variables
  features <- input$select_subset_{{ env_id }}
  if(input$select_group_feat_{{ env_id }} != "None") group_by_feat <- input$select_group_feat_{{ env_id }} else group_by_feat <- NULL
  if(input$select_group_meta_{{ env_id }} != "None") group_by_meta <- input$select_group_meta_{{ env_id }} else group_by_meta <- NULL
  if(!is.null(group_by_meta)) group_by <- group_by_meta else group_by <- group_by_feat
  
  if(input$select_colour_feat_{{ env_id }} != "None") colour_by_feat <- input$select_colour_feat_{{ env_id }} else colour_by_feat <- NULL
  if(input$select_colour_meta_{{ env_id }} != "None") colour_by_meta <- input$select_colour_meta_{{ env_id }} else colour_by_meta <- NULL
  if(!is.null(colour_by_meta)) colour_by <- colour_by_meta else colour_by <- colour_by_feat
  
  if(input$select_shape_feat_{{ env_id }} != "None") shape_by_feat <- input$select_shape_feat_{{ env_id }} else shape_by_feat <- NULL
  if(input$select_shape_meta_{{ env_id }} != "None") shape_by_meta <- input$select_shape_meta_{{ env_id }} else shape_by_meta <- NULL
  if(!is.null(shape_by_meta)) shape_by <- shape_by_meta else shape_by <- shape_by_feat

  if(input$select_size_feat_{{ env_id }} != "None") size_by_feat <- input$select_size_feat_{{ env_id }} else size_by_feat <- NULL
  if(input$select_size_meta_{{ env_id }} != "None") size_by_meta <- input$select_size_meta_{{ env_id }} else size_by_meta <- NULL
  if(!is.null(size_by_meta)) size_by <- size_by_meta else size_by <- size_by_feat
  
  ncols <- input$select_ncol_{{ env_id }}
  scales <- input$select_scales_{{ env_id }}
  
  params <- list(
    object = {{ env_id }}$object,
    features = features,
    x = group_by,
    exprs_values = {{ env_id }}$exprs_values,
    colour_by = colour_by,
    shape_by = shape_by,
    size_by = size_by,
    ncol = ncols
  )
  params <- append(params, {{ env_id }}$params)
  return(params)
})

# create default plot for the first start of the page
default_plot <- reactiveVal(TRUE)
observeEvent(input$generate_{{ env_id }},{
  val <- FALSE
  default_plot(val)
})

# Generate plot
reactive_plot_{{ env_id }} <- shiny::eventReactive(input$generate_{{ env_id }},{
  # create plot
  plot <- do.call(scater::plotExpression, reactive_{{ env_id }}())
  
  # handle titles
  if(!is.null({{ env_id }}$plot_title)) plot <- plot + ggplot2::ggtitle({{ env_id }}$plot_title)
  if(!is.null({{ env_id }}$x_title)) plot <- plot + ggplot2::xlab({{ env_id }}$x_title)
  if(!is.null({{ env_id }}$y_title)) plot <- plot + ggplot2::ylab({{ env_id }}$y_title)
  return(plot)
})

# Download data.frame
output$downloadData_{{ env_id }} <- downloadHandler(
  filename =  paste('data-', Sys.Date(), '.csv', sep=''),
  content = function(file) {
    df <- data.frame(SummarizedExperiment::assay({{ env_id }}$object, {{ env_id }}$exprs_values)[reactive_{{ env_id }}()$features,])
    # todo: add metadata to the df
    write.csv(df, file)
  }
)

# Plot output as plotly or ggplot2
if(!{{ env_id }}$as_plotly){
  # plot output
  output$plot_{{ env_id }} <- renderPlot({
    if(default_plot()){
      plot <- scater::plotExpression(
        object = {{ env_id }}$object,
        features = {{ env_id }}$features[1],
        x = {{ env_id }}$x,
        exprs_values = {{ env_id }}$exprs_values,
        ncol = {{ env_id }}$ncols
      )
      # handle titles
      if(!is.null({{ env_id }}$plot_title)) plot <- plot + ggplot2::ggtitle({{ env_id }}$plot_title)
      if(!is.null({{ env_id }}$x_title)) plot <- plot + ggplot2::xlab({{ env_id }}$x_title)
      if(!is.null({{ env_id }}$y_title)) plot <- plot + ggplot2::ylab({{ env_id }}$y_title)
      plot
    } else {
      reactive_plot_{{ env_id }}()
    }
  })
  # lauyout
  shiny::fillRow(
    flex = c(NA, 1),
    shinyWidgets::dropdownButton(
      div(style = 'max-height: 350px; overflow-x: auto;', do.call(shiny::inputPanel, ui_list)),
      circle = TRUE,
      status = "danger",
      icon = icon("gear"),
      width = "300px",
      tooltip = shinyWidgets::tooltipOptions(title = "Click, to change plot settings:")
    ),
    plotOutput("plot_{{ env_id }}")
  )
} else if ({{ env_id }}$as_plotly){
  # plot output
  output$plot_{{ env_id }} <- plotly::renderPlotly({
    if(default_plot()){
      plot <- scater::plotExpression(
        object = {{ env_id }}$object,
        features = {{ env_id }}$features[1],
        x = {{ env_id }}$x,
        exprs_values = {{ env_id }}$exprs_values,
        ncol = {{ env_id }}$ncols
      )
      # handle titles
      if(!is.null({{ env_id }}$plot_title)) plot <- plot + ggplot2::ggtitle({{ env_id }}$plot_title)
      if(!is.null({{ env_id }}$x_title)) plot <- plot + ggplot2::xlab({{ env_id }}$x_title)
      if(!is.null({{ env_id }}$y_title)) plot <- plot + ggplot2::ylab({{ env_id }}$y_title)
      plot
    } else {
      reactive_plot_{{ env_id }}()
    }
  })
  # lauyout
  shiny::fillRow(
    flex = c(NA, 1),
    shinyWidgets::dropdownButton(
      div(style = 'max-height: 350px; overflow-x: auto;', do.call(shiny::inputPanel, ui_list)),
      circle = TRUE,
      status = "danger",
      icon = icon("gear"),
      width = "300px",
      tooltip = shinyWidgets::tooltipOptions(title = "Click, to change plot settings:")
    ),
    plotly::plotlyOutput("plot_{{ env_id }}", height = "100%")
  )
}
```


