
### {{ title }}

<!-- Component created on {{ date }} -->

```{r}
{{ env_id }} <- readRDS(file.path(datadir, "{{ env_id }}.rds"))
is_shiny <- identical(knitr::opts_knit$get("rmarkdown.runtime"), "shiny")
library(magrittr)
library(scater)
library(SummarizedExperiment)
```

```{r, eval=!is_shiny}
# create plot according to colData or rowData
if({{ env_id }}$from == "colData"){
  plot_{{ env_id }} <- scater::plotColData(
    object = {{ env_id }}$object,
    y = {{ env_id }}$y[1],
    x = {{ env_id }}$x[1],
    colour_by = {{ env_id }}$metadata[1]
  )
} else {
  plot_{{ env_id }} <- scater::plotRowData(
    object = {{ env_id }}$object,
    y = {{ env_id }}$y[1],
    x = {{ env_id }}$x[1],
    colour_by = {{ env_id }}$metadata[1]
  )
}
# handle grouping
if(!is.null({{ env_id }}$group_by)){
  if(is.numeric(SummarizedExperiment::colData({{ env_id }}$object)[{{ env_id }}$y][[3]]) | is.numeric(SummarizedExperiment::colData({{ env_id }}$object)[{{ env_id }}$x][[1]])){
    plot_{{ env_id }} <- plot_{{ env_id }} + facet_wrap({{ env_id }}$object[[{{ env_id }}$group_by]])
  }
}
# handle titles
if(!is.null({{ env_id }}$plot_title)){
  plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::ggtitle({{ env_id }}$plot_title)
}
if(!is.null({{ env_id }}$x_title)){
  plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::xlab({{ env_id }}$x_title)
}
if(!is.null({{ env_id }}$y_title)){
  plot_{{ env_id }} <- plot_{{ env_id }} + ggplot2::ylab({{ env_id }}$y_title)
}
# handle if as_plotly = TRUE
if({{ env_id }}$as_plotly){
  plot_{{ env_id }} <- plotly::ggplotly(plot_{{ env_id }})
}
# Provide data for download
if({{ env_id }}$from == "colData"){
  download_{{ env_id }} <- data.frame(colData({{ env_id }}$object))
} else {
  download_{{ env_id }} <- data.frame(rowData({{ env_id }}$object))
}

plot_{{ env_id }}

# to do: provide data for download, but the ggplot2 plot cannot be displayed in the div container
# Provide data for download
# if({{ env_id }}$from == "colData"){
#   download_{{ env_id }} <- data.frame(colData({{ env_id }}$object)[,c({{ env_id }}$y[1], {{ env_id }}$x[1], {{ env_id }}$metadata[1])])
# } else {
#   download_{{ env_id }} <- data.frame(rowData({{ env_id }}$object)[,c({{ env_id }}$y[1], {{ env_id }}$x[1], {{ env_id }}$metadata[1])])
# }

# generate component
# htmltools::div(style="display:block;float:left;width:100%;height:90%;",
#   htmltools::tags$button(i2dash::embed_var(download_{{ env_id }})), plot_{{ env_id }})
#htmltools::tags$button(i2dash::embed_var(download_{{ env_id }}))
```

```{r, eval=is_shiny}
# shiny input elements
ui_list <- list(
  # y
  selectInput("select_y_{{ env_id }}", label = "Select data for y-axis:", choices = {{ env_id }}$y),
  # x
  selectInput("select_x_{{ env_id }}", label = "Select data for x-axis:", choices = c("None", {{ env_id }}$x), selected = {{ env_id }}$x[1]),
  # colour_by
  selectInput("select_colour_by_{{ env_id }}", label = "Colour by:", choices = c("None", {{ env_id }}$metadata), selected = {{ env_id }}$metadata[1]),
  # shape_by
  selectInput("select_shape_by_{{ env_id }}", label = "Shape by:", choices = c("None", {{ env_id }}$metadata)),
  # size_by
  selectInput("select_size_by_{{ env_id }}", label = "Size by:", choices = c("None", {{ env_id }}$metadata)),
  # group_by
  selectInput("select_group_by_{{ env_id }}", label = "Group by:", choices = c("None", {{ env_id }}$metadata), selected = {{ env_id }}$group_by),
  # as_plotly
  #radioButtons("radio_{{ env_id }}", label = "Select visualization:", choices = c("ggplot2", "plotly")),
  # download
  tags$div(tags$br(), downloadButton('downloadData_{{ env_id }}', 'Download data'))
)

# create plot
reactive_{{ env_id }} <- shiny::reactive({
  # set variables
  y <- input$select_y_{{ env_id }}
  if(input$select_x_{{ env_id }} != "None") x <- input$select_x_{{ env_id }} else x <- NULL
  if(input$select_colour_by_{{ env_id }} != "None") colour_by <- input$select_colour_by_{{ env_id }} else colour_by <- NULL
  if(input$select_shape_by_{{ env_id }} != "None") shape_by <- input$select_shape_by_{{ env_id }} else shape_by <- NULL
  if(input$select_size_by_{{ env_id }} != "None") size_by <- input$select_size_by_{{ env_id }} else size_by <- NULL
  if(input$select_group_by_{{ env_id }} != "None") group_by <- input$select_group_by_{{ env_id }} else group_by <- NULL
  
  # create plot according to colData or rowData
  if({{ env_id }}$from == "colData"){
    plot <- scater::plotColData(
      object = {{ env_id }}$object,
      y = y,
      x = x,
      colour_by = colour_by,
      shape_by = shape_by,
      size_by = size_by
    )
  } else {
    plot <- scater::plotRowData(
      object = {{ env_id }}$object,
      y = y,
      x = x,
      colour_by = colour_by,
      shape_by = shape_by,
      size_by = size_by
    )
  }
  # handle grouping
  if(!is.null(group_by)){
    if(is.numeric(SummarizedExperiment::colData({{ env_id }}$object)[[y]]) | is.numeric(SummarizedExperiment::colData({{ env_id }}$object)[[x]])){
      plot <- plot + facet_wrap({{ env_id }}$object[[group_by]])
    }
  }
  # handle titles
  if(!is.null({{ env_id }}$plot_title)){
    plot <- plot + ggplot2::ggtitle({{ env_id }}$plot_title)
  }
  if(!is.null({{ env_id }}$x_title)){
    plot <- plot + ggplot2::xlab({{ env_id }}$x_title)
  }
  if(!is.null({{ env_id }}$y_title)){
    plot <- plot + ggplot2::ylab({{ env_id }}$y_title)
  }
  return(plot)
})

# Download data.frame
output$downloadData_{{ env_id }} <- downloadHandler(
  filename =  paste('data-', Sys.Date(), '.csv', sep=''),
  content = function(file) {
    if({{ env_id }}$from == "colData"){
      df <- data.frame(colData({{ env_id }}$object))
    } else {
      df <- data.frame(rowData({{ env_id }}$object))
    }
    write.csv(df, file)
  }
)

if(!{{ env_id }}$as_plotly){
  # plot output
  output$plot_{{ env_id }} <- renderPlot({
    reactive_{{ env_id }}()
  })
  # lauyout
  shiny::fillRow(
    flex = c(NA, 1),
    shinyWidgets::dropdownButton(
      div(style = 'max-height: 350px; overflow-x: auto;', do.call(shiny::inputPanel, ui_list)),
      circle = TRUE,
      status = "danger",
      icon = icon("gear"),
      width = "300px",
      tooltip = shinyWidgets::tooltipOptions(title = "Click, to change plot settings:")
    ),
    plotOutput("plot_{{ env_id }}")
  )
} else if ({{ env_id }}$as_plotly){
  # plot output
  output$plot_{{ env_id }} <- plotly::renderPlotly({
    reactive_{{ env_id }}()
  })
  # lauyout
  shiny::fillRow(
    flex = c(NA, 1),
    shinyWidgets::dropdownButton(
      div(style = 'max-height: 350px; overflow-x: auto;', do.call(shiny::inputPanel, ui_list)),
      circle = TRUE,
      status = "danger",
      icon = icon("gear"),
      width = "300px",
      tooltip = shinyWidgets::tooltipOptions(title = "Click, to change plot settings:")
    ),
    plotly::plotlyOutput("plot_{{ env_id }}", height = "100%")
  )
}
```


