
### {{ title }}

<!-- Component created on {{ date }} -->

```{r}
{{ env_id }} <- readRDS(file.path(datadir, "{{ env_id }}.rds"))
library(magrittr)
```

```{r}
# selecting the first numeric and factor column for object wrapper 
{{ env_id }}$df %>%
  kableExtra::kable() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
  kableExtra::footnote(general = {{ env_id }}$footnote_text,
                       general_title = {{ env_id }}$footnote_title,
                       footnote_as_chunk = T,
                       title_format = c("bold", "underline")) -> {{ env_id }}_kable

# prepare a header vector for kableExtra::add_header_above
if(!is.null({{ env_id }}$group_by)){
  {{ env_id }}_level_nr <- length(unique({{ env_id }}$group_by))
  {{ env_id }}_FUNS_nr <- length({{ env_id }}$FUNS)
  {{ env_id }}_header_vector <- c(1, rep({{ env_id }}_level_nr, {{ env_id }}_FUNS_nr))
  names({{ env_id }}_header_vector) <- c(" ", {{ env_id }}$FUNS)
  {{ env_id }}_kable %<>%
    kableExtra::add_header_above({{ env_id }}_header_vector)
}

# Provide data for download
{{ env_id }}_df <- {{ env_id }}$df
if(!is.null({{ env_id }}$group_by)){
  fun_vector <- unlist(lapply({{ env_id }}$FUNS, rep, times = length(unique({{ env_id }}$group_by))))
  colnames({{ env_id }}_df) <- paste0(colnames({{ env_id }}_df),"_", fun_vector)
}
{{ env_id }}_kable
htmltools::tags$button(i2dash::embed_var({{ env_id }}_df)) 
```


